const Card = [
    {
      id: 1,
      image: "https://picsum.photos/200/300?random=1",
      name: "Ramesh Agrawal",
     name2: "Redhe Sweets",
      mobile: "Mobile: +91-88712144839",
      email: "Email: rameshagrawal@gmail.com",
      code: "GSTIN: 36ABDFM7977nIZD",
      pan: "Download PAN",
      gstin: "Download GSTIN",
      tan: "Download TAN",
      contact: "Download Contact",
    },
    {
        id: 2,
        image: "https://picsum.photos/200/300?random=1",
        name: "Ramesh Agrawal",
       name2: "Redhe Sweets",
        mobile: "Mobile: +91-88712144839",
        email: "Email: rameshagrawal@gmail.com",
        code: "GSTIN: 36ABDFM7977nIZD",
        pan: "Download PAN",
        gstin: "Download GSTIN",
        tan: "Download TAN",
        contact: "Download Contact",
      },
      {
        id: 3,
        image: "https://picsum.photos/200/300?random=1",
        name: "Ramesh Agrawal",
       name2: "Redhe Sweets",
        mobile: "Mobile: +91-88712144839",
        email: "Email: rameshagrawal@gmail.com",
        code: "GSTIN: 36ABDFM7977nIZD",
        pan: "Download PAN",
        gstin: "Download GSTIN",
        tan: "Download TAN",
        contact: "Download Contact",
      },
      {
        id: 4,
        image: "https://picsum.photos/200/300?random=1",
        name: "Ramesh Agrawal",
       name2: "Redhe Sweets",
        mobile: "Mobile: +91-88712144839",
        email: "Email: rameshagrawal@gmail.com",
        code: "GSTIN: 36ABDFM7977nIZD",
        pan: "Download PAN",
        gstin: "Download GSTIN",
        tan: "Download TAN",
        contact: "Download Contact",
      },
      {
        id: 5,
        image: "https://picsum.photos/200/300?random=1",
        name: "Ramesh Agrawal",
       name2: "Redhe Sweets",
        mobile: "Mobile: +91-88712144839",
        email: "Email: rameshagrawal@gmail.com",
        code: "GSTIN: 36ABDFM7977nIZD",
        pan: "Download PAN",
        gstin: "Download GSTIN",
        tan: "Download TAN",
        contact: "Download Contact",
      },
      {
        id: 6,
        image: "https://picsum.photos/200/300?random=1",
        name: "Ramesh Agrawal",
       name2: "Redhe Sweets",
        mobile: "Mobile: +91-88712144839",
        email: "Email: rameshagrawal@gmail.com",
        code: "GSTIN: 36ABDFM7977nIZD",
        pan: "Download PAN",
        gstin: "Download GSTIN",
        tan: "Download TAN",
        contact: "Download Contact",
      },
]